version: '2'
services:
  ktan-app:
    image: ktan
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://ktan-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ktan
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8085:8085
  ktan-mongodb:
    extends:
      file: mongodb.yml
      service: ktan-mongodb
